### ISSUE TITLE
Laravel 7 Compatibility

### ISSUE THREAD

**Issue by devr-team** [fisharebest/laravel-floats#3]
Hello, can you please make this package compatible with Laravel 7? 

Thank you.

composer require fisharebest/laravel-floats
Using version ^1.3 for fisharebest/laravel-floats
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fisharebest/laravel-floats ^1.3 -> satisfiable by fisharebest/laravel-floats[1.3.0].
    - Installation request for laravel/framework (locked at v7.21.0, required as ^7.0) -> satisfiable by laravel/framework[v7.21.0].

**Comment by fisharebest** [comment]
Thanks for reporting this.

I have just released 1.4.0, which adds compatibility with Laravel 7.x
